#SPDX-License-Identifier: MIT-0
---
# vars file for system_configuration

rootssh_pubkeys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE7ZOMNjVWsP226l62ttQFOBbGs/OrzyygtT02cyjMtZ nsd@nsvivo"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1uh9VJNzVIv2EdsEELD52VpNNTBiJU1lodzkBcc1hueQgBcF7ocSeWWG/IydqwuEFWYIzinE0K79b3DthYaDBWoox7WZBwYctFdCc+oMv7JT0fH55FHYZSdXIhNzxPHmypKPcAzpMRgeNDtRxUfcITXzP+VJ/nbQqVmacO0ZpTr9PU+t3jWNRBhfJ8U439azfeQucwsVHZbeYDT8hXms8MoZR9NbVAc3vq1ZenfZD+vFBp1zWFzKsG7y9p/57Xy2IX0/Y+QBqyn0QYB2xqJK8XcIVG7pxpiHgJadJH7VJj06PN1LmDPOlvZTg2qDLg12bCE9yvZjzvEzFvFed74FfEX3N8WXbHK+TDO9PR/S16pL/Rl6jyEOBPhz1WILU5GsEkhaZUv4LNnJ/O1bIswkNCAFQ1igS/Nht7Yh9UpbAaUn9O9DEyXAkdyaCl6542jxf07a7Z2n0NxROQY1MWmATdKkwYrJJibJXWgY9VtNF9hirIK51QS397DSWcEYOMJFuG7zoVuM/vVWu4Qqd/YHgcatgsHpB6FvBE0v2QtN1lzpRgWLQ0m6WIl54Zo1XsZJvUpclJ/dB4lHaxKBF8ONvADYh0KlhHccstPKidt9tausamMgYRQTMBQ+x75F/lUgO3a4Y6LzozKgK2oONSe9NWAZyvhqBR2bJ+t1I8pmMUw== nsd@nsbox4096"

syslogger: "syslog-ng"
crondaemon: "cronie"