#SPDX-License-Identifier: MIT-0
---
# defaults file for system_configuration
hostname: "genserver"
gentoo_init: "openrc"
rootfs_mountpoint: "/mnt/gentoo"
disks:
  - "/dev/nvme0n1"
  - "/dev/nvme1n1"
partitions:
  - { name: "efi", size: "256MiB", type: "primary", fs_type: "vfat" }
  - { name: "boot", size: "1GiB", type: "primary", fs_type: "ext4" }
  - { name: "lvmpv", size: "100%", type: "primary", fs_type: "lvm" }
lvm_vg: "gentoo_vg"
lvm_lvs:
  - { name: "root", size: "20g", fs_type: "btrfs", mountpoint: "/" }
  - { name: "home", size: "20g", fs_type: "btrfs", mountpoint: "/home" }
