#SPDX-License-Identifier: MIT-0
---
# tasks file for disks_prepare
- name: Create partitions

- name: Setup RAID1

- name: Setup LVM VG

- name: Create LVM volumes

- name: Format partitions

- name: Mount root FS

- name: Create mountpoints

- name: Mount boot partitions

- name: Extract latest Gentoo Stage3
  creates: "{{ mountpoint }}/etc/gentoo-release
